#!/usr/bin/perl
use esmith::NetworksDB;
my $ndb = esmith::NetworksDB->open_ro();
my $db = esmith::ConfigDB->open_ro();
my $docker = $db->get_prop('docker','access') || '';
my $IP;

if (($docker eq 'green') || ($docker eq 'private')) {
    if (defined($ndb->green)) {
        @greens = $ndb->green;
         $IP = $greens['0']->prop('ipaddr');
    }
}

elsif (($docker =~ 'red') || ($docker eq 'public')) {
    if (defined($ndb->red)){
        @reds = $ndb->red;
        $IP = $reds['0']->prop('ipaddr');
    }
}

elsif ($docker =~ 'orange') {
    if (defined($ndb->orange)){
        @oranges = $ndb->orange;
        $IP = $oranges['0']->prop('ipaddr');
    }
}

elsif ($docker =~ 'blue') {
    if (defined($ndb->blue)){
        @blues = $ndb->blue;
        $IP = $blues['0']->prop('ipaddr');
    }
}

print $IP;
