#!/usr/bin/bash

event=$1
#pid=`/usr/sbin/pidof traefik`


#if [[ $pid -ne '' ]]; then
    /usr/bin/docker container stop traefik-container || exit 1
    /usr/bin/docker rm -f traefik-container || exit 1
#fi

docker run -d \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    -v /etc/traefik/traefik.toml:/traefik.toml \
    -p 80:80 \
    -p 443:443 \
    -l traefik.port=8080 \
    --restart unless-stopped \
    --name traefik-container \
    traefik:1.5.4-alpine --docker || exit 1

#    -l traefik.frontend.rule=Host:monitor.example.com \

#/usr/bin/docker run -d -p 9000:9000 --restart unless-stopped --name portainer-container \
#    -v portainer-data:/data -v "/var/run/docker.sock:/var/run/docker.sock" \
#    -v /etc/pki/tls/:/certs:ro portainer/portainer --ssl --sslcert "${crt}" \
#    --sslkey "${key}" -H unix:///var/run/docker.sock || exit 1
